"""WMO CAP 1.2 XML alert scaffold for avalanche forecast products.

Generates OASIS Common Alerting Protocol (CAP) 1.2 XML from forecast
artifacts. This is a scaffold — it produces valid XML structure but
does not submit to any national emergency pathway. Validation against
the CAP 1.2 XSD should be done before production use.

Reference: https://docs.oasis-open.org/emergency/cap/v1.2/CAP-v1.2.html
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from typing import Any
from xml.etree import ElementTree as ET

CAP_NAMESPACE = 'urn:oasis:names:tc:emergency:cap:1.2'
CAP_VERSION = '1.2'
ALERT_TRIGGER_DANGER_LEVEL = int(os.getenv('ALERT_TRIGGER_DANGER_LEVEL', '4'))
CAP_ENABLED = os.getenv('CAP_ENABLED', 'false').lower() not in {'0', 'false', 'off', 'no'}

EAWS_DANGER_TO_CAP_SEVERITY = {
    1: 'Minor',
    2: 'Minor',
    3: 'Moderate',
    4: 'Severe',
    5: 'Extreme',
}

EAWS_DANGER_TO_CAP_CERTAINTY = {
    1: 'Possible',
    2: 'Possible',
    3: 'Likely',
    4: 'Likely',
    5: 'Observed',
}

# F16: Multi-language alert text templates
MULTI_LANGUAGE_INFO: dict[str, dict[str, str]] = {
    'en-US': {
        'event': 'Avalanche Warning',
        'headline': 'Avalanche Warning — {region_name} — EAWS Level {danger_level}',
        'description': (
            'Batch-first avalanche forecast for {region_name} ({region_key}). '
            'Forecast date: {forecast_date}. Horizon: {horizon_hours}h. '
            'Maximum EAWS danger level: {danger_level}. '
            'This is a decision-support tool, not an official warning.'
        ),
        'instruction': (
            'Consult local avalanche bulletins for official warnings. '
            'This forecast is generated by a batch-first ML pipeline and '
            'should be used as supplementary decision support only.'
        ),
    },
    'hi': {
        'event': 'हिमस्खलन चेतावनी',
        'headline': 'हिमस्खलन चेतावनी — {region_name} — EAWS स्तर {danger_level}',
        'description': (
            '{region_name} ({region_key}) के लिए बैच-फर्स्ट हिमस्खलन पूर्वानुमान. '
            'पूर्वानुमान तिथि: {forecast_date}. क्षितिज: {horizon_hours}घंटे. '
            'अधिकतम EAWS खतरा स्तर: {danger_level}. '
            'यह एक निर्णय-सहायता उपकरण है, आधिकारिक चेतावनी नहीं.'
        ),
        'instruction': (
            'आधिकारिक चेतावनियों के लिए स्थानीय हिमस्खलन बुलेटिन देखें. '
            'यह पूर्वानुमान एक बैच-फर्स्ट ML पाइपलाइन द्वारा तैयार किया गया है.'
        ),
    },
    'ur': {
        'event': 'برفانی تودے کی تنبیہ',
        'headline': 'برفانی تودے کی تنبیہ — {region_name} — EAWS سطح {danger_level}',
        'description': (
            '{region_name} ({region_key}) کے لیے بیچ-فرسٹ برفانی تودے کی پیش گوئی. '
            'پیش گوئی کی تاریخ: {forecast_date}. افق: {horizon_hours}گھنٹے. '
            'زیادہ سے زیادہ EAWS خطرے کی سطح: {danger_level}. '
            'یہ ایک فیصلہ-معاون آلہ ہے، سرکاری تنبیہ نہیں.'
        ),
        'instruction': (
            'سرکاری تنبیہوں کے لیے مقامی برفانی تودے کا بلیٹن دیکھیں. '
            'یہ پیش گوئی ایک بیچ-فرسٹ ML پائپ لائن سے تیار کی گئی ہے.'
        ),
    },
}


def should_trigger_alert(danger_level: int, threshold: int = ALERT_TRIGGER_DANGER_LEVEL) -> bool:
    """Determine if a CAP alert should be triggered.

    Args:
        danger_level: EAWS danger level (1-5)
        threshold: Trigger threshold (default 4)

    Returns:
        True if danger_level >= threshold
    """
    return danger_level >= threshold


def check_cap_publication_gates(
    *,
    source_freshness_hours: dict[str, float] | None = None,
    lineage_verified: bool = False,
    has_synthetic_evidence: bool = False,
    max_freshness_hours: float = 72.0,
) -> tuple[bool, str | None]:
    """Check publication gates before emitting a CAP alert.

    Blocks CAP alert generation when:
    - Any source freshness exceeds max_freshness_hours
    - Lineage is not verified
    - Evidence contains synthetic/unreviewed data

    Args:
        source_freshness_hours: Dict of source name → hours since acquisition.
        lineage_verified: Whether scene lineage has been verified.
        has_synthetic_evidence: Whether any evidence is synthetic/unreviewed.
        max_freshness_hours: Maximum allowed freshness (default 72h).

    Returns:
        (allowed, reason) — reason is None if allowed, else a human-readable block reason.
    """
    if not lineage_verified:
        return False, 'CAP blocked: lineage not verified'

    if has_synthetic_evidence:
        return False, 'CAP blocked: synthetic/unreviewed evidence present'

    if source_freshness_hours:
        stale_sources = [
            name for name, hours in source_freshness_hours.items()
            if hours is not None and hours > max_freshness_hours
        ]
        if stale_sources:
            return False, f'CAP blocked: stale sources ({", ".join(stale_sources)})'

    return True, None


def validate_cap_xml(xml_string: str) -> tuple[bool, str | None]:
    """Validate CAP XML string is well-formed and has required elements.

    Performs structural validation against CAP 1.2 requirements.
    Full XSD validation requires the CAP 1.2 XSD file.

    Args:
        xml_string: CAP XML string to validate

    Returns:
        (is_valid, error_message) — error_message is None if valid
    """
    try:
        root = ET.fromstring(xml_string)
    except ET.ParseError as exc:
        return (False, f'XML parse error: {exc}')

    ns = {'cap': CAP_NAMESPACE}

    # Check required top-level elements
    required_top = ['identifier', 'sender', 'sent', 'status', 'msgType', 'scope']
    for elem_name in required_top:
        elem = root.find(f'cap:{elem_name}', ns)
        if elem is None:
            elem = root.find(elem_name)
        if elem is None or not (elem.text or '').strip():
            return (False, f'Missing required element: {elem_name}')

    # Check at least one info block exists
    info_blocks = root.findall('cap:info', ns)
    if not info_blocks:
        info_blocks = root.findall('info')
    if not info_blocks:
        return (False, 'Missing required info block')

    # Check required info elements
    required_info = ['category', 'event', 'urgency', 'severity', 'certainty']
    for info in info_blocks:
        for elem_name in required_info:
            elem = info.find(f'cap:{elem_name}', ns)
            if elem is None:
                elem = info.find(elem_name)
            if elem is None or not (elem.text or '').strip():
                return (False, f'Missing required info element: {elem_name}')

    return (True, None)


def generate_cap_alert(
    *,
    identifier: str,
    sender: str,
    sent: datetime | None = None,
    status: str = 'Actual',
    message_type: str = 'Alert',
    scope: str = 'Public',
    region_name: str,
    region_key: str,
    bbox: list[float],
    forecast_date: str,
    horizon_hours: int,
    max_danger_level: int,
    headline: str,
    description: str,
    instruction: str | None = None,
    web_url: str | None = None,
    effective: datetime | None = None,
    expires: datetime | None = None,
) -> str:
    """Generate a CAP 1.2 XML alert string from forecast parameters.

    Args:
        identifier: Unique alert identifier (e.g., forecast_run_id).
        sender: Sender identifier (e.g., 'avalanche-insight-hub@system').
        sent: Issue timestamp (defaults to now UTC).
        status: CAP status (Actual, Exercise, System, Test, Draft).
        message_type: CAP message type (Alert, Update, Cancel, Ack, Error).
        scope: CAP scope (Public, Restricted, Private).
        region_name: Human-readable region name.
        region_key: Machine region key.
        bbox: [west, south, east, north] bounding box.
        forecast_date: ISO date string for the forecast.
        horizon_hours: Forecast horizon in hours.
        max_danger_level: EAWS danger level 1-5.
        headline: Short headline for the alert.
        description: Detailed description of the avalanche risk.
        instruction: Recommended actions (optional).
        web_url: URL to the full forecast workspace (optional).
        effective: Effective time (defaults to sent).
        expires: Expiry time (defaults to sent + horizon_hours).

    Returns:
        CAP 1.2 XML string.
    """
    sent = sent or datetime.now(timezone.utc)
    effective = effective or sent
    expires = expires or sent.replace() if False else sent

    from datetime import timedelta
    expires = expires or (sent + timedelta(hours=horizon_hours))

    severity = EAWS_DANGER_TO_CAP_SEVERITY.get(max_danger_level, 'Moderate')
    certainty = EAWS_DANGER_TO_CAP_CERTAINTY.get(max_danger_level, 'Possible')

    area_desc = f'{region_name} ({region_key}) — bbox: {bbox[0]},{bbox[1]},{bbox[2]},{bbox[3]}'

    info = ET.Element('info', xmlns=CAP_NAMESPACE)
    ET.SubElement(info, 'language').text = 'en-US'
    ET.SubElement(info, 'category').text = 'Met'
    ET.SubElement(info, 'event').text = 'Avalanche Warning'
    ET.SubElement(info, 'urgency').text = 'Expected'
    ET.SubElement(info, 'severity').text = severity
    ET.SubElement(info, 'certainty').text = certainty
    ET.SubElement(info, 'effective').text = effective.isoformat()
    ET.SubElement(info, 'expires').text = expires.isoformat()
    ET.SubElement(info, 'senderName').text = 'Avalanche Insight Hub'
    ET.SubElement(info, 'headline').text = headline
    ET.SubElement(info, 'description').text = description
    if instruction:
        ET.SubElement(info, 'instruction').text = instruction
    ET.SubElement(info, 'web').text = web_url or ''
    ET.SubElement(info, 'parameter', name='forecastDate').text = forecast_date
    ET.SubElement(info, 'parameter', name='horizonHours').text = str(horizon_hours)
    ET.SubElement(info, 'parameter', name='eawsDangerLevel').text = str(max_danger_level)
    ET.SubElement(info, 'parameter', name='regionKey').text = region_key

    area = ET.SubElement(info, 'area')
    ET.SubElement(area, 'areaDesc').text = area_desc
    polygon = f'{bbox[1]},{bbox[0]} {bbox[1]},{bbox[2]} {bbox[3]},{bbox[2]} {bbox[3]},{bbox[0]} {bbox[1]},{bbox[0]}'
    ET.SubElement(area, 'polygon').text = polygon

    alert = ET.Element('alert')
    alert.set('xmlns', CAP_NAMESPACE)
    ET.SubElement(alert, 'identifier').text = identifier
    ET.SubElement(alert, 'sender').text = sender
    ET.SubElement(alert, 'sent').text = sent.isoformat()
    ET.SubElement(alert, 'status').text = status
    ET.SubElement(alert, 'msgType').text = message_type
    ET.SubElement(alert, 'scope').text = scope
    alert.append(info)

    ET.indent(alert, space='  ')
    return ET.tostring(alert, encoding='unicode', xml_declaration=True)


def generate_cap_from_forecast_run(
    forecast_run: dict[str, Any],
    *,
    sender: str = 'avalanche-insight-hub@system',
    web_url: str | None = None,
) -> str:
    """Generate CAP XML from a forecast run dictionary.

    Args:
        forecast_run: Dictionary with keys matching forecast_runs table columns.
        sender: CAP sender identifier.
        web_url: URL to the public forecast workspace.

    Returns:
        CAP 1.2 XML string.
    """
    model_metadata = forecast_run.get('model_metadata') or {}
    weather_summary = forecast_run.get('weather_summary') or {}
    bulletins = forecast_run.get('forecast_bulletins') or {}

    max_danger = 1
    for bulletin in bulletins.values() if isinstance(bulletins, dict) else []:
        if isinstance(bulletin, dict):
            level = bulletin.get('danger_level') or bulletin.get('maxDangerLevel')
            if isinstance(level, (int, float)) and level > max_danger:
                max_danger = int(level)

    region_name = forecast_run.get('region_name') or forecast_run.get('region_key', 'unknown')
    region_key = forecast_run.get('region_key', 'unknown')
    bbox = forecast_run.get('bbox', [0, 0, 0, 0])
    forecast_date = str(forecast_run.get('forecast_date', ''))
    horizon_hours = int(forecast_run.get('horizon_hours', 72))

    headline = f'Avalanche Warning — {region_name} — EAWS Level {max_danger}'
    description = (
        f'Batch-first avalanche forecast for {region_name} ({region_key}). '
        f'Forecast date: {forecast_date}. Horizon: {horizon_hours}h. '
        f'Maximum EAWS danger level: {max_danger}. '
        f'Model: {model_metadata.get("model_version", "unknown")}. '
        f'This is a decision-support tool, not an official warning.'
    )
    instruction = (
        'Consult local avalanche bulletins for official warnings. '
        'This forecast is generated by a batch-first ML pipeline and '
        'should be used as supplementary decision support only.'
    )

    return generate_cap_alert(
        identifier=str(forecast_run.get('id', 'unknown')),
        sender=sender,
        region_name=region_name,
        region_key=region_key,
        bbox=bbox,
        forecast_date=forecast_date,
        horizon_hours=horizon_hours,
        max_danger_level=max_danger,
        headline=headline,
        description=description,
        instruction=instruction,
        web_url=web_url,
    )


def generate_multi_language_cap(
    *,
    identifier: str,
    sender: str,
    region_name: str,
    region_key: str,
    bbox: list[float],
    forecast_date: str,
    horizon_hours: int,
    max_danger_level: int,
    languages: list[str] | None = None,
    web_url: str | None = None,
) -> str:
    """Generate CAP 1.2 XML with multi-language info blocks.

    Args:
        languages: List of language codes ('en-US', 'hi', 'ur').
                   Defaults to all three.

    Returns:
        CAP 1.2 XML string with one info block per language.
    """
    langs = languages or ['en-US', 'hi', 'ur']
    sent = datetime.now(timezone.utc)
    severity = EAWS_DANGER_TO_CAP_SEVERITY.get(max_danger_level, 'Moderate')
    certainty = EAWS_DANGER_TO_CAP_CERTAINTY.get(max_danger_level, 'Possible')
    area_desc = f'{region_name} ({region_key}) — bbox: {bbox[0]},{bbox[1]},{bbox[2]},{bbox[3]}'
    polygon = f'{bbox[1]},{bbox[0]} {bbox[1]},{bbox[2]} {bbox[3]},{bbox[2]} {bbox[3]},{bbox[0]} {bbox[1]},{bbox[0]}'

    alert = ET.Element('alert')
    alert.set('xmlns', CAP_NAMESPACE)
    ET.SubElement(alert, 'identifier').text = identifier
    ET.SubElement(alert, 'sender').text = sender
    ET.SubElement(alert, 'sent').text = sent.isoformat()
    ET.SubElement(alert, 'status').text = 'Actual'
    ET.SubElement(alert, 'msgType').text = 'Alert'
    ET.SubElement(alert, 'scope').text = 'Public'

    for lang in langs:
        templates = MULTI_LANGUAGE_INFO.get(lang, MULTI_LANGUAGE_INFO['en-US'])
        info = ET.SubElement(alert, 'info')
        ET.SubElement(info, 'language').text = lang
        ET.SubElement(info, 'category').text = 'Met'
        ET.SubElement(info, 'event').text = templates['event']
        ET.SubElement(info, 'urgency').text = 'Expected'
        ET.SubElement(info, 'severity').text = severity
        ET.SubElement(info, 'certainty').text = certainty
        ET.SubElement(info, 'effective').text = sent.isoformat()
        ET.SubElement(info, 'expires').text = sent.isoformat()
        ET.SubElement(info, 'senderName').text = 'Avalanche Insight Hub'
        ET.SubElement(info, 'headline').text = templates['headline'].format(
            region_name=region_name, danger_level=max_danger_level,
        )
        ET.SubElement(info, 'description').text = templates['description'].format(
            region_name=region_name, region_key=region_key,
            forecast_date=forecast_date, horizon_hours=horizon_hours,
            danger_level=max_danger_level,
        )
        ET.SubElement(info, 'instruction').text = templates['instruction']
        ET.SubElement(info, 'web').text = web_url or ''
        ET.SubElement(info, 'parameter', name='forecastDate').text = forecast_date
        ET.SubElement(info, 'parameter', name='horizonHours').text = str(horizon_hours)
        ET.SubElement(info, 'parameter', name='eawsDangerLevel').text = str(max_danger_level)
        ET.SubElement(info, 'parameter', name='regionKey').text = region_key

        area = ET.SubElement(info, 'area')
        ET.SubElement(area, 'areaDesc').text = area_desc
        ET.SubElement(area, 'polygon').text = polygon

    ET.indent(alert, space='  ')
    return ET.tostring(alert, encoding='unicode', xml_declaration=True)
