import { useState } from 'react';
import { AlertTriangle, ChevronDown } from 'lucide-react';
import { cn } from '@/lib/utils';

const DISCLAIMER_KEY = 'avalanche-disclaimer-expanded';

export default function ExpandableDisclaimer() {
  const [expanded, setExpanded] = useState(() => {
    try {
      return localStorage.getItem(DISCLAIMER_KEY) === 'true';
    } catch {
      return false;
    }
  });

  const toggle = () => {
    const next = !expanded;
    setExpanded(next);
    try {
      localStorage.setItem(DISCLAIMER_KEY, String(next));
    } catch {
      // ignore
    }
  };

  return (
    <div className="border-b border-amber-500/15 bg-amber-500/5 backdrop-blur-sm">
      <div className="mx-auto max-w-[1600px] px-4 sm:px-6 lg:px-8">
        <button
          onClick={toggle}
          className="flex w-full items-center gap-2 py-2 text-left"
          aria-expanded={expanded}
          aria-controls="disclaimer-details"
        >
          <AlertTriangle className="h-3.5 w-3.5 shrink-0 text-amber-400" />
          <span className="text-xs leading-tight text-amber-400/90">
            <strong>Experimental AI system</strong> — Not for life-critical decisions. Use official avalanche centers where available.
          </span>
          <ChevronDown
            className={cn(
              'ml-auto h-3.5 w-3.5 shrink-0 text-amber-400/60 transition-transform duration-200',
              expanded && 'rotate-180',
            )}
          />
        </button>
        {expanded && (
          <div id="disclaimer-details" className="pb-3 text-xs leading-relaxed text-muted-foreground">
            <p className="mb-1.5">
              This platform is a <strong className="text-foreground">decision-support prototype</strong> that renders
              published technical artifacts. It is not an official avalanche warning service and should not
              be used for operational decisions.
            </p>
            <p className="mb-1.5">
              Forecasts are generated by a Random Forest surrogate model (RF4) trained on Swiss Alps data
              (EnviDat/WSL). Transferability to other regions (Himalayas, Andes, etc.) is <em>unvalidated</em>.
              Snowpack variables are weather-derived proxies, not thermodynamic model outputs.
            </p>
            <p>
              Always consult <a href="https://avalanche.org" target="_blank" rel="noopener noreferrer" className="text-emerald-400/80 hover:text-emerald-400 underline">official avalanche centers</a> for
              operational avalanche safety decisions.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
