// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function requireEnv(name: string, value: string | undefined) {
  if (!value) {
    throw new Error(
      `${name} is missing. Create .env.local from .env.local.example and set it before running the app.`,
    );
  }

  return value;
}

const SUPABASE_URL = requireEnv('VITE_SUPABASE_URL', import.meta.env.VITE_SUPABASE_URL);
const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ??
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_API_KEY = requireEnv('VITE_SUPABASE_ANON_KEY or VITE_SUPABASE_PUBLISHABLE_KEY', SUPABASE_ANON_KEY);

export { SUPABASE_API_KEY as SUPABASE_ANON_KEY };

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_API_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
